// Template registry. Each template composes palette + decoration + fonts + copy.
// Keep IDs short & stable — they go into share URLs.
export const TEMPLATES = [
  // ---------- LOVE ----------
  {
    id: "love-rose",
    name: "Rose Garden",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-dancing",
      title: "With All My Love",
      emoji: "🌹",
    },
    inside: {
      palette: "rose",
      decoration: "none",
      font: "font-caveat",
    },
    reveal: "burst",
  },
  {
    id: "love-tum-ho",
    name: "Tum Ho",
    category: "love",
    lang: "hi",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "तुम हो तो सब है",
      emoji: "💖",
    },
    inside: {
      palette: "lavender",
      decoration: "none",
      font: "font-devanagari",
    },
    reveal: "rise",
  },
  {
    id: "love-valentine",
    name: "Be Mine",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-playfair",
      title: "Happy Valentine's Day",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- BIRTHDAY ----------
  {
    id: "bday-confetti",
    name: "Confetti Pop",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-playfair",
      title: "Happy Birthday!",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "bday-balloons",
    name: "Balloon Party",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "balloons",
      titleFont: "font-dancing",
      title: "Make a Wish",
      emoji: "🎈",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "bday-janamdin",
    name: "Janamdin Mubarak",
    category: "birthday",
    lang: "hi",
    cover: {
      palette: "amber",
      decoration: "balloons",
      titleFont: "font-devanagari",
      title: "जन्मदिन मुबारक",
      emoji: "🎉",
    },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },

  // ---------- FRIENDSHIP ----------
  {
    id: "friend-bestie",
    name: "Best Friend",
    category: "friendship",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-caveat",
      title: "To My Favourite Human",
      emoji: "🌟",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "friend-yaar",
    name: "Yaari",
    category: "friendship",
    lang: "hi",
    cover: {
      palette: "mint",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "मेरे यार के नाम",
      emoji: "🤝",
    },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- FESTIVAL ----------
  {
    id: "fest-diwali",
    name: "Diwali Lights",
    category: "festival",
    lang: "en",
    cover: {
      palette: "diya",
      decoration: "diyas",
      titleFont: "font-playfair",
      title: "Happy Diwali",
      emoji: "🪔",
    },
    inside: { palette: "diya", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-holi",
    name: "Holi Hai",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "holi",
      decoration: "colors",
      titleFont: "font-devanagari",
      title: "होली है!",
      emoji: "🎨",
    },
    inside: { palette: "holi", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "fest-eid",
    name: "Eid Mubarak",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Eid Mubarak",
      emoji: "🌙",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "fest-rakhi",
    name: "Raksha Bandhan",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "amber",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "रक्षा बंधन मुबारक",
      emoji: "🪢",
    },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "fest-christmas",
    name: "Merry Christmas",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "Merry Christmas",
      emoji: "🎄",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-new-year",
    name: "Happy New Year",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "confetti",
      titleFont: "font-playfair",
      title: "Happy New Year",
      emoji: "🎆",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- SORRY ----------
  {
    id: "sorry-soft",
    name: "I'm Sorry",
    category: "sorry",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "I'm Sorry",
      emoji: "🥺",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "sorry-forgive",
    name: "Forgive Me",
    category: "sorry",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "geometric",
      titleFont: "font-dancing",
      title: "Please Forgive Me",
      emoji: "🙇",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "sorry-maafi",
    name: "Maafi",
    category: "sorry",
    lang: "hi",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "माफ़ कर दो",
      emoji: "🤍",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- THANK YOU ----------
  {
    id: "thanks-grateful",
    name: "Thank You",
    category: "thanks",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "Thank You",
      emoji: "🙏",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "thanks-much-appreciated",
    name: "Much Appreciated",
    category: "thanks",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "You are a Gem",
      emoji: "✨",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "thanks-shukriya",
    name: "Shukriya",
    category: "thanks",
    lang: "hi",
    cover: {
      palette: "mint",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "शुक्रिया",
      emoji: "🌿",
    },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- MISS YOU ----------
  {
    id: "miss-you-moon",
    name: "Missing You",
    category: "miss",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "I Miss You",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "miss-you-thinkingof",
    name: "Thinking of You",
    category: "miss",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "hearts",
      titleFont: "font-dancing",
      title: "Thinking of You",
      emoji: "💭",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "miss-yaad-aati",
    name: "Yaad Aati Hai",
    category: "miss",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "तुम्हारी याद आती है",
      emoji: "🕯️",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- MORE LOVE VARIETY ----------
  {
    id: "love-forever",
    name: "Forever Yours",
    category: "love",
    lang: "en",
    cover: {
      palette: "amber",
      decoration: "hearts",
      titleFont: "font-playfair",
      title: "Forever Yours",
      emoji: "💫",
    },
    inside: { palette: "amber", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "love-anniversary",
    name: "Happy Anniversary",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Happy Anniversary",
      emoji: "💞",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },

  // ---------- MORE BIRTHDAY ----------
  {
    id: "bday-minimal",
    name: "Another Year",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "mint",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Another Year Wiser",
      emoji: "🍰",
    },
    inside: { palette: "mint", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "bday-milestone",
    name: "Big Day",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "confetti",
      titleFont: "font-dancing",
      title: "It's Your Big Day!",
      emoji: "🥳",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- MORE FRIENDSHIP ----------
  {
    id: "friend-thanks-being-there",
    name: "Thanks for Being You",
    category: "friendship",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "Thanks for Being You",
      emoji: "💛",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },

  // ---------- EVERYDAY ----------
  {
    id: "everyday-good-night",
    name: "Good Night",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Good Night",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-good-morning",
    name: "Good Morning",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Good Morning",
      emoji: "☀️",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "everyday-nice-day",
    name: "Have a Nice Day",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "mint",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Have a Nice Day",
      emoji: "🌼",
    },
    inside: { palette: "mint", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-get-well",
    name: "Get Well Soon",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "Get Well Soon",
      emoji: "🌷",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-congrats",
    name: "Congrats!",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-dancing",
      title: "Congratulations!",
      emoji: "🎊",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "शुभ रात्रि",
      emoji: "🌃",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- VALENTINE'S WEEK (Feb 7-14) ----------
  {
    id: "vw-rose-day",
    name: "Rose Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-dancing",
      title: "Happy Rose Day",
      emoji: "🌹",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "vw-propose-day",
    name: "Propose Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "Will You Be Mine?",
      emoji: "💍",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-chocolate-day",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "amber",
      decoration: "chocolate-rain",
      titleFont: "font-dancing",
      title: "Happy Chocolate Day",
      emoji: "🍫",
    },
    inside: { palette: "amber", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "vw-teddy-day",
    name: "Teddy Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "teddy-drift",
      titleFont: "font-dancing",
      title: "Happy Teddy Day",
      emoji: "🧸",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-promise-day",
    name: "Promise Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "My Promise to You",
      emoji: "🤞",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "vw-hug-day",
    name: "Hug Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "cupid-hearts",
      titleFont: "font-dancing",
      title: "Sending You a Hug",
      emoji: "🤗",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-kiss-day",
    name: "Kiss Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petal-shower",
      titleFont: "font-dancing",
      title: "A Kiss for You",
      emoji: "💋",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "vw-valentines",
    name: "Happy Valentine's",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-playfair",
      title: "Be My Valentine",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- MORE FESTIVALS (rich) ----------
  {
    id: "fest-ganesh",
    name: "Ganesh Chaturthi",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "diya",
      decoration: "diya-glow",
      titleFont: "font-devanagari",
      title: "गणपति बाप्पा मोरया",
      emoji: "🕉️",
    },
    inside: { palette: "diya", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "fest-janmashtami",
    name: "Janmashtami",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "sparkle-trail",
      titleFont: "font-devanagari",
      title: "जय श्री कृष्ण",
      emoji: "🦚",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "fest-navratri",
    name: "Navratri",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "holi",
      decoration: "petal-shower",
      titleFont: "font-devanagari",
      title: "नवरात्रि की शुभकामनाएँ",
      emoji: "🪷",
    },
    inside: { palette: "holi", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "fest-pongal",
    name: "Pongal",
    category: "festival",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "Happy Pongal",
      emoji: "🌾",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "fest-onam",
    name: "Onam",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "petal-shower",
      titleFont: "font-playfair",
      title: "Happy Onam",
      emoji: "🌼",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "fest-diwali-rich",
    name: "Diwali Glow",
    category: "festival",
    lang: "en",
    cover: {
      palette: "diya",
      decoration: "diya-glow",
      titleFont: "font-playfair",
      title: "Shubh Deepawali",
      emoji: "🪔",
    },
    inside: { palette: "diya", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-new-year-rich",
    name: "New Year Fireworks",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "firework-bursts",
      titleFont: "font-dancing",
      title: "Happy New Year!",
      emoji: "🎆",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-christmas-rich",
    name: "Christmas Snow",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "snow-fall",
      titleFont: "font-dancing",
      title: "Merry Christmas",
      emoji: "🎄",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },

  // ---------- MORE RICH EVERYDAY / LOVE ----------
  {
    id: "everyday-sweet-dreams",
    name: "Sweet Dreams",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "sparkle-trail",
      titleFont: "font-dancing",
      title: "Sweet Dreams",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "love-always",
    name: "I Love You Always",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-dancing",
      title: "I Love You, Always",
      emoji: "💖",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "birthday-rich-wish",
    name: "Birthday Wish",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "ribbon-drift",
      titleFont: "font-dancing",
      title: "Wishing You the Moon",
      emoji: "🎁",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "miss-long-distance",
    name: "Across the Miles",
    category: "miss",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "cupid-hearts",
      titleFont: "font-playfair",
      title: "Across the Miles",
      emoji: "✈️",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },

  // ---------- REGIONAL LANGUAGES ----------
  {
    id: "regional-marathi-vadhdiwas",
    name: "Vadhdivas",
    category: "birthday",
    lang: "mr",
    cover: {
      palette: "sunset",
      decoration: "balloons",
      titleFont: "font-marathi",
      title: "वाढदिवसाच्या हार्दिक शुभेच्छा",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "regional-marathi-prem",
    name: "Prem",
    category: "love",
    lang: "mr",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-marathi",
      title: "तू माझं सर्वस्व",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "regional-tamil-piranthanaal",
    name: "Piranthanaal",
    category: "birthday",
    lang: "ta",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-tamil",
      title: "பிறந்தநாள் வாழ்த்துக்கள்",
      emoji: "🎉",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "regional-tamil-nandri",
    name: "Nandri",
    category: "thanks",
    lang: "ta",
    cover: {
      palette: "emerald",
      decoration: "petals",
      titleFont: "font-tamil",
      title: "நன்றி",
      emoji: "🙏",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "regional-bangla-shubho-jonmodin",
    name: "Shubho Jonmodin",
    category: "birthday",
    lang: "bn",
    cover: {
      palette: "indigo",
      decoration: "balloons",
      titleFont: "font-bangla",
      title: "শুভ জন্মদিন",
      emoji: "🎈",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "regional-bangla-bhalobasha",
    name: "Bhalobasha",
    category: "love",
    lang: "bn",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-bangla",
      title: "তোমায় ভালোবাসি",
      emoji: "💗",
    },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },

  // ---------- GUJARATI ----------
  {
    id: "regional-gujarati-janmadin",
    name: "Janmadin Mubarak",
    category: "birthday",
    lang: "gu",
    cover: {
      palette: "sunset",
      decoration: "balloons",
      titleFont: "font-gujarati",
      title: "જન્મદિવસ મુબારક",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "regional-gujarati-prem",
    name: "Prem",
    category: "love",
    lang: "gu",
    cover: {
      palette: "rose",
      decoration: "petals",
      titleFont: "font-gujarati",
      title: "હું તને પ્રેમ કરું છું",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },

  // ---------- KANNADA ----------
  {
    id: "regional-kannada-hutthabbada",
    name: "Hutthabbada Shubhashaya",
    category: "birthday",
    lang: "kn",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-kannada",
      title: "ಹುಟ್ಟುಹಬ್ಬದ ಶುಭಾಶಯಗಳು",
      emoji: "🎉",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-kannada" },
    reveal: "burst",
  },
  {
    id: "regional-kannada-preethi",
    name: "Preethi",
    category: "love",
    lang: "kn",
    cover: {
      palette: "lavender",
      decoration: "hearts",
      titleFont: "font-kannada",
      title: "ನಿನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೇನೆ",
      emoji: "💞",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-kannada" },
    reveal: "burst",
  },

  // ---------- TELUGU ----------
  {
    id: "regional-telugu-puttinarojushubhakanksha",
    name: "Puttinaroju Shubhakanksha",
    category: "birthday",
    lang: "te",
    cover: {
      palette: "mint",
      decoration: "balloons",
      titleFont: "font-telugu",
      title: "పుట్టినరోజు శుభాకాంక్షలు",
      emoji: "🎈",
    },
    inside: { palette: "mint", decoration: "none", font: "font-telugu" },
    reveal: "rise",
  },
  {
    id: "regional-telugu-prema",
    name: "Prema",
    category: "love",
    lang: "te",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-telugu",
      title: "నిన్ను ప్రేమిస్తున్నాను",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-telugu" },
    reveal: "burst",
  },

  // ---------- PUNJABI (GURMUKHI) ----------
  {
    id: "regional-punjabi-janamdin",
    name: "Janamdin",
    category: "birthday",
    lang: "pa",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-gurmukhi",
      title: "ਜਨਮਦਿਨ ਮੁਬਾਰਕ",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "regional-punjabi-pyaar",
    name: "Pyaar",
    category: "love",
    lang: "pa",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-gurmukhi",
      title: "ਮੈਂ ਤੈਨੂੰ ਪਿਆਰ ਕਰਦਾ ਹਾਂ",
      emoji: "💘",
    },
    inside: { palette: "rose", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },

  // ================ MARATHI (mr) — full replication ================
  // Love
  {
    id: "mr-love-prem",
    name: "Prem",
    category: "love",
    lang: "mr",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-marathi", title: "तुझ्यावर प्रेम आहे", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-love-sarvasva",
    name: "Sarvasva",
    category: "love",
    lang: "mr",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-marathi", title: "तू माझं सर्वस्व", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-love-anniversary",
    name: "Lagnacha Vadhdivas",
    category: "love",
    lang: "mr",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-marathi", title: "लग्नाच्या वाढदिवसाच्या शुभेच्छा", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "mr-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "mr",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-marathi", title: "गुलाबाच्या शुभेच्छा", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "mr",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-marathi", title: "तू माझी/माझा होशील?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "mr",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-marathi", title: "चॉकलेट डे शुभेच्छा", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },
  {
    id: "mr-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "mr",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-marathi", title: "एक मिठी तुझ्यासाठी", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "mr",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-marathi", title: "व्हॅलेंटाइनच्या शुभेच्छा", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },

  // Birthday
  {
    id: "mr-bday-hardik",
    name: "Vadhdivas",
    category: "birthday",
    lang: "mr",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-marathi", title: "वाढदिवसाच्या हार्दिक शुभेच्छा", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-bday-balloons",
    name: "Shubh Vadhdivas",
    category: "birthday",
    lang: "mr",
    cover: { palette: "indigo", decoration: "balloons", titleFont: "font-marathi", title: "शुभ वाढदिवस", emoji: "🎈" },
    inside: { palette: "indigo", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-bday-wish",
    name: "Mangalmay",
    category: "birthday",
    lang: "mr",
    cover: { palette: "lavender", decoration: "ribbon-drift", titleFont: "font-marathi", title: "तुझा दिवस मंगलमय होवो", emoji: "🎁" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },

  // Friendship
  {
    id: "mr-friend-maitri",
    name: "Maitri",
    category: "friendship",
    lang: "mr",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-marathi", title: "माझ्या दोस्ताच्या नावाने", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },
  {
    id: "mr-friend-dosti",
    name: "Dosti Kayam",
    category: "friendship",
    lang: "mr",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-marathi", title: "दोस्ती कायम", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },

  // Festivals
  {
    id: "mr-fest-gudi-padwa",
    name: "Gudi Padwa",
    category: "festival",
    lang: "mr",
    cover: { palette: "sunset", decoration: "petal-shower", titleFont: "font-marathi", title: "शुभ गुढी पाडवा", emoji: "🌸" },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-fest-ganpati",
    name: "Ganpati Bappa",
    category: "festival",
    lang: "mr",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-marathi", title: "गणपती बाप्पा मोरया", emoji: "🕉️" },
    inside: { palette: "diya", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-fest-diwali",
    name: "Diwali",
    category: "festival",
    lang: "mr",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-marathi", title: "शुभ दीपावली", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "mr-fest-rakhi",
    name: "Raksha Bandhan",
    category: "festival",
    lang: "mr",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-marathi", title: "रक्षाबंधनाच्या शुभेच्छा", emoji: "🪢" },
    inside: { palette: "amber", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-fest-new-year",
    name: "Navvarsh",
    category: "festival",
    lang: "mr",
    cover: { palette: "midnight", decoration: "firework-bursts", titleFont: "font-marathi", title: "नववर्षाच्या शुभेच्छा", emoji: "🎆" },
    inside: { palette: "midnight", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },

  // Everyday
  {
    id: "mr-everyday-shubh-sakal",
    name: "Shubh Sakal",
    category: "everyday",
    lang: "mr",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-marathi", title: "शुभ सकाळ", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "rise",
  },
  {
    id: "mr-everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "mr",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-marathi", title: "शुभ रात्री", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },
  {
    id: "mr-everyday-get-well",
    name: "Lavkar Bare Vha",
    category: "everyday",
    lang: "mr",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-marathi", title: "लवकर बरे व्हा", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },
  {
    id: "mr-everyday-abhinandan",
    name: "Abhinandan",
    category: "everyday",
    lang: "mr",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-marathi", title: "अभिनंदन!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "mr-thanks-dhanyavad",
    name: "Dhanyavad",
    category: "thanks",
    lang: "mr",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-marathi", title: "धन्यवाद", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "mr-miss-aathvan",
    name: "Aathvan",
    category: "miss",
    lang: "mr",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-marathi", title: "तुझी आठवण येते", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },

  // Sorry
  {
    id: "mr-sorry-maaf",
    name: "Maaf Kar",
    category: "sorry",
    lang: "mr",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-marathi", title: "माफ कर", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-marathi" },
    reveal: "fade",
  },

  // ================ HINDI (hi) — expansion ================
  // Love
  {
    id: "hi-love-tumse-hi",
    name: "Tum Se Hi",
    category: "love",
    lang: "hi",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-devanagari", title: "तुम से ही सब है", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "hi-love-dil-tumhara",
    name: "Dil Tumhara",
    category: "love",
    lang: "hi",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-devanagari", title: "दिल तुम्हारा है", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "hi-love-anniversary",
    name: "Salgirah",
    category: "love",
    lang: "hi",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-devanagari", title: "सालगिरह मुबारक", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "hi-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "hi",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-devanagari", title: "गुलाब की शुभकामनाएँ", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "hi-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "hi",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-devanagari", title: "क्या तुम मेरी/मेरे बनोगी/बनोगे?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "hi",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-devanagari", title: "चॉकलेट डे मुबारक", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "hi",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-devanagari", title: "एक झप्पी तुम्हारे नाम", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "hi",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-devanagari", title: "वैलेंटाइन्स डे मुबारक", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },

  // Birthday
  {
    id: "hi-bday-hardik",
    name: "Hardik Shubhkamnaen",
    category: "birthday",
    lang: "hi",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-devanagari", title: "जन्मदिन की हार्दिक शुभकामनाएँ", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "hi-bday-wish",
    name: "Badhai Ho",
    category: "birthday",
    lang: "hi",
    cover: { palette: "lavender", decoration: "balloons", titleFont: "font-devanagari", title: "बधाई हो, जन्मदिन मुबारक!", emoji: "🎈" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-bday-gift",
    name: "Tohfa",
    category: "birthday",
    lang: "hi",
    cover: { palette: "indigo", decoration: "ribbon-drift", titleFont: "font-devanagari", title: "आज का दिन तुम्हारा है", emoji: "🎁" },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // Friendship
  {
    id: "hi-friend-pakka-dost",
    name: "Pakka Dost",
    category: "friendship",
    lang: "hi",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-devanagari", title: "सच्चे दोस्त के लिए", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-friend-salamat",
    name: "Dosti Salamat",
    category: "friendship",
    lang: "hi",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-devanagari", title: "दोस्ती सलामत रहे", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // Festivals
  {
    id: "hi-fest-diwali-rich",
    name: "Shubh Deepawali",
    category: "festival",
    lang: "hi",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-devanagari", title: "शुभ दीपावली", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "hi-fest-eid",
    name: "Eid Mubarak",
    category: "festival",
    lang: "hi",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-devanagari", title: "ईद मुबारक", emoji: "🌙" },
    inside: { palette: "emerald", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-fest-karwa-chauth",
    name: "Karwa Chauth",
    category: "festival",
    lang: "hi",
    cover: { palette: "rose", decoration: "diya-glow", titleFont: "font-devanagari", title: "करवा चौथ मुबारक", emoji: "🌕" },
    inside: { palette: "rose", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-fest-bhai-dooj",
    name: "Bhai Dooj",
    category: "festival",
    lang: "hi",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-devanagari", title: "भाई दूज मुबारक", emoji: "🪔" },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-fest-christmas",
    name: "Christmas",
    category: "festival",
    lang: "hi",
    cover: { palette: "emerald", decoration: "snow-fall", titleFont: "font-devanagari", title: "क्रिसमस मुबारक", emoji: "🎄" },
    inside: { palette: "emerald", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-fest-new-year",
    name: "Nav Varsh",
    category: "festival",
    lang: "hi",
    cover: { palette: "midnight", decoration: "firework-bursts", titleFont: "font-devanagari", title: "नव वर्ष मुबारक", emoji: "🎆" },
    inside: { palette: "midnight", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },

  // Everyday
  {
    id: "hi-everyday-suprabhat",
    name: "Suprabhat",
    category: "everyday",
    lang: "hi",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-devanagari", title: "सुप्रभात", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "hi-everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "hi",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-devanagari", title: "शुभ रात्रि", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-everyday-sweet-dreams",
    name: "Meethe Sapne",
    category: "everyday",
    lang: "hi",
    cover: { palette: "midnight", decoration: "sparkle-trail", titleFont: "font-devanagari", title: "मीठे सपने", emoji: "✨" },
    inside: { palette: "midnight", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-everyday-get-well",
    name: "Jaldi Theek Ho",
    category: "everyday",
    lang: "hi",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-devanagari", title: "जल्दी ठीक हो जाओ", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-everyday-badhai",
    name: "Badhai Ho",
    category: "everyday",
    lang: "hi",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-devanagari", title: "बधाई हो!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "hi-thanks-shukriya",
    name: "Shukriya",
    category: "thanks",
    lang: "hi",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-devanagari", title: "शुक्रिया", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-thanks-dhanyavad",
    name: "Dhanyavad",
    category: "thanks",
    lang: "hi",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-devanagari", title: "तहे दिल से धन्यवाद", emoji: "✨" },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "hi-miss-bahut-yaad",
    name: "Bahut Yaad",
    category: "miss",
    lang: "hi",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-devanagari", title: "बहुत याद आते हो", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "hi-miss-thinking-of-you",
    name: "Sochta Hoon",
    category: "miss",
    lang: "hi",
    cover: { palette: "indigo", decoration: "hearts", titleFont: "font-devanagari", title: "तुम्हारे ख़यालों में हूँ", emoji: "💌" },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },

  // Sorry
  {
    id: "hi-sorry-kshama",
    name: "Kshama",
    category: "sorry",
    lang: "hi",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-devanagari", title: "मुझे माफ़ कर दो", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ================ BENGALI (bn) — full coverage ================
  // Love
  {
    id: "bn-love-bhalobasi",
    name: "Bhalobasi",
    category: "love",
    lang: "bn",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-bangla", title: "তোমায় ভালোবাসি", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-love-tumi-sob",
    name: "Tumi Amar Shob",
    category: "love",
    lang: "bn",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-bangla", title: "তুমিই আমার সব", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-love-anniversary",
    name: "Anniversary",
    category: "love",
    lang: "bn",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-bangla", title: "শুভ বিবাহবার্ষিকী", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "bn-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "bn",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-bangla", title: "শুভ রোজ ডে", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "bn",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-bangla", title: "তুমি কি আমার হবে?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "bn-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "bn",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-bangla", title: "শুভ চকলেট ডে", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "bn",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-bangla", title: "একটা আলিঙ্গন তোমার জন্য", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "bn-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "bn",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-bangla", title: "শুভ ভ্যালেন্টাইনস ডে", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },

  // Birthday (existing bn-regional-bangla-shubho-jonmodin already exists)
  {
    id: "bn-bday-shubhechha",
    name: "Shubhechha",
    category: "birthday",
    lang: "bn",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-bangla", title: "জন্মদিনের শুভেচ্ছা", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-bday-wish",
    name: "Birthday Wish",
    category: "birthday",
    lang: "bn",
    cover: { palette: "lavender", decoration: "ribbon-drift", titleFont: "font-bangla", title: "তোমার দিন শুভ হোক", emoji: "🎁" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // Friendship
  {
    id: "bn-friend-bondhu",
    name: "Bondhu",
    category: "friendship",
    lang: "bn",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-bangla", title: "বন্ধুর জন্য", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-friend-forever",
    name: "Bondhutto Chirodin",
    category: "friendship",
    lang: "bn",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-bangla", title: "বন্ধুত্ব চিরদিন", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // Festivals (Bengal-specific)
  {
    id: "bn-fest-durga-puja",
    name: "Durga Puja",
    category: "festival",
    lang: "bn",
    cover: { palette: "amber", decoration: "petal-shower", titleFont: "font-bangla", title: "শুভ দুর্গা পূজা", emoji: "🪷" },
    inside: { palette: "amber", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-fest-bijoya",
    name: "Bijoya Dashami",
    category: "festival",
    lang: "bn",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-bangla", title: "শুভ বিজয়া দশমী", emoji: "🌺" },
    inside: { palette: "sunset", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "bn-fest-pohela-boishakh",
    name: "Pohela Boishakh",
    category: "festival",
    lang: "bn",
    cover: { palette: "sunset", decoration: "petal-shower", titleFont: "font-bangla", title: "শুভ নববর্ষ", emoji: "🌾" },
    inside: { palette: "sunset", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-fest-saraswati",
    name: "Saraswati Puja",
    category: "festival",
    lang: "bn",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-bangla", title: "সরস্বতী পূজার শুভেচ্ছা", emoji: "🪷" },
    inside: { palette: "amber", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-fest-kali-diwali",
    name: "Kali Puja",
    category: "festival",
    lang: "bn",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-bangla", title: "শুভ দীপাবলি", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
  {
    id: "bn-fest-eid",
    name: "Eid Mubarak",
    category: "festival",
    lang: "bn",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-bangla", title: "ঈদ মুবারক", emoji: "🌙" },
    inside: { palette: "emerald", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-fest-christmas",
    name: "Christmas",
    category: "festival",
    lang: "bn",
    cover: { palette: "emerald", decoration: "snow-fall", titleFont: "font-bangla", title: "শুভ বড়দিন", emoji: "🎄" },
    inside: { palette: "emerald", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // Everyday
  {
    id: "bn-everyday-shubh-shokal",
    name: "Shubh Shokal",
    category: "everyday",
    lang: "bn",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-bangla", title: "শুভ সকাল", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "bn-everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "bn",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-bangla", title: "শুভ রাত্রি", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-everyday-get-well",
    name: "Get Well Soon",
    category: "everyday",
    lang: "bn",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-bangla", title: "দ্রুত সুস্থ হয়ে ওঠো", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },
  {
    id: "bn-everyday-congrats",
    name: "Obhinondon",
    category: "everyday",
    lang: "bn",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-bangla", title: "অভিনন্দন!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "bn-thanks-dhonnobad",
    name: "Dhonnobad",
    category: "thanks",
    lang: "bn",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-bangla", title: "ধন্যবাদ", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "bn-miss-miss-kori",
    name: "Miss Kori",
    category: "miss",
    lang: "bn",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-bangla", title: "তোমাকে মিস করি", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // Sorry
  {
    id: "bn-sorry-khoma-koro",
    name: "Khoma Koro",
    category: "sorry",
    lang: "bn",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-bangla", title: "আমাকে ক্ষমা করো", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-bangla" },
    reveal: "fade",
  },

  // ================ GUJARATI (gu) — full coverage ================
  // Love
  {
    id: "gu-love-prem-karu",
    name: "Prem Karu Chhu",
    category: "love",
    lang: "gu",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-gujarati", title: "તને પ્રેમ કરું છું", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-love-tu-ja-badhu",
    name: "Tu Ja Madhu",
    category: "love",
    lang: "gu",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-gujarati", title: "તું જ મારું બધું", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-love-anniversary",
    name: "Anniversary",
    category: "love",
    lang: "gu",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-gujarati", title: "લગ્ન જીવનના શુભ વર્ષ", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "gu-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "gu",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-gujarati", title: "શુભ રોઝ ડે", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "gu",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-gujarati", title: "મારી/મારો બનીશ?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },
  {
    id: "gu-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "gu",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-gujarati", title: "શુભ ચોકલેટ ડે", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },
  {
    id: "gu-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "gu",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-gujarati", title: "એક ગલે તારા માટે", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },
  {
    id: "gu-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "gu",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-gujarati", title: "શુભ વેલેન્ટાઇન્સ ડે", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },

  // Birthday (one existing, adding 3)
  {
    id: "gu-bday-shubhechha",
    name: "Shubhechha",
    category: "birthday",
    lang: "gu",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-gujarati", title: "જન્મદિવસની શુભેચ્છાઓ", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-bday-wish",
    name: "Birthday Wish",
    category: "birthday",
    lang: "gu",
    cover: { palette: "lavender", decoration: "ribbon-drift", titleFont: "font-gujarati", title: "તારો દિવસ ખુશીઓથી ભરેલો હોય", emoji: "🎁" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // Friendship
  {
    id: "gu-friend-mitra",
    name: "Mitra",
    category: "friendship",
    lang: "gu",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-gujarati", title: "મિત્ર માટે", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },
  {
    id: "gu-friend-dosti",
    name: "Dosti Kayam",
    category: "friendship",
    lang: "gu",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-gujarati", title: "દોસ્તી કાયમ", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // Festivals (Gujarat-heavy)
  {
    id: "gu-fest-navratri",
    name: "Navratri",
    category: "festival",
    lang: "gu",
    cover: { palette: "holi", decoration: "petal-shower", titleFont: "font-gujarati", title: "શુભ નવરાત્રી", emoji: "🪷" },
    inside: { palette: "holi", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-fest-uttarayan",
    name: "Uttarayan",
    category: "festival",
    lang: "gu",
    cover: { palette: "sunset", decoration: "sparkle-trail", titleFont: "font-gujarati", title: "શુભ ઉત્તરાયણ", emoji: "🪁" },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },
  {
    id: "gu-fest-diwali",
    name: "Diwali",
    category: "festival",
    lang: "gu",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-gujarati", title: "શુભ દીપાવલી", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-fest-bestu-varas",
    name: "Bestu Varas",
    category: "festival",
    lang: "gu",
    cover: { palette: "sunset", decoration: "firework-bursts", titleFont: "font-gujarati", title: "સાલ મુબારક", emoji: "🎆" },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-fest-janmashtami",
    name: "Janmashtami",
    category: "festival",
    lang: "gu",
    cover: { palette: "indigo", decoration: "sparkle-trail", titleFont: "font-gujarati", title: "જય શ્રી કૃષ્ણ", emoji: "🦚" },
    inside: { palette: "indigo", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },
  {
    id: "gu-fest-rakhi",
    name: "Raksha Bandhan",
    category: "festival",
    lang: "gu",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-gujarati", title: "રક્ષા બંધનની શુભેચ્છાઓ", emoji: "🪢" },
    inside: { palette: "amber", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },
  {
    id: "gu-fest-holi",
    name: "Holi",
    category: "festival",
    lang: "gu",
    cover: { palette: "holi", decoration: "colors", titleFont: "font-gujarati", title: "હેપી હોળી", emoji: "🎨" },
    inside: { palette: "holi", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },
  {
    id: "gu-fest-eid",
    name: "Eid",
    category: "festival",
    lang: "gu",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-gujarati", title: "ઈદ મુબારક", emoji: "🌙" },
    inside: { palette: "emerald", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // Everyday
  {
    id: "gu-everyday-shubh-savar",
    name: "Shubh Savar",
    category: "everyday",
    lang: "gu",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-gujarati", title: "શુભ સવાર", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "rise",
  },
  {
    id: "gu-everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "gu",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-gujarati", title: "શુભ રાત્રિ", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },
  {
    id: "gu-everyday-get-well",
    name: "Jaldi Sara Thao",
    category: "everyday",
    lang: "gu",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-gujarati", title: "જલ્દી સારા થઈ જાઓ", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },
  {
    id: "gu-everyday-abhinandan",
    name: "Abhinandan",
    category: "everyday",
    lang: "gu",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-gujarati", title: "અભિનંદન!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-gujarati" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "gu-thanks-aabhar",
    name: "Aabhar",
    category: "thanks",
    lang: "gu",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-gujarati", title: "આભાર", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "gu-miss-yaad-aave",
    name: "Yaad Aave",
    category: "miss",
    lang: "gu",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-gujarati", title: "ખૂબ યાદ આવે છે", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // Sorry
  {
    id: "gu-sorry-maafi",
    name: "Maafi",
    category: "sorry",
    lang: "gu",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-gujarati", title: "મને માફ કરો", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-gujarati" },
    reveal: "fade",
  },

  // ================ PUNJABI (pa) — full coverage ================
  // Love
  {
    id: "pa-love-pyaar",
    name: "Pyaar",
    category: "love",
    lang: "pa",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-gurmukhi", title: "ਮੈਂ ਤੈਨੂੰ ਪਿਆਰ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-love-sab-kuch",
    name: "Tu Hi Sab Kuch",
    category: "love",
    lang: "pa",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-gurmukhi", title: "ਤੂੰ ਹੀ ਮੇਰਾ ਸਭ ਕੁਝ", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-love-anniversary",
    name: "Anniversary",
    category: "love",
    lang: "pa",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-gurmukhi", title: "ਸਾਲਗਿਰਾ ਮੁਬਾਰਕ", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "pa-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "pa",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-gurmukhi", title: "ਗੁਲਾਬ ਦੀਆਂ ਸ਼ੁਭਕਾਮਨਾਵਾਂ", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "pa",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-gurmukhi", title: "ਕੀ ਤੂੰ ਮੇਰੀ/ਮੇਰਾ ਬਣੇਂਗੀ/ਬਣੇਂਗਾ?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },
  {
    id: "pa-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "pa",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-gurmukhi", title: "ਚਾਕਲੇਟ ਡੇ ਮੁਬਾਰਕ", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },
  {
    id: "pa-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "pa",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-gurmukhi", title: "ਇੱਕ ਜੱਫੀ ਤੇਰੇ ਲਈ", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },
  {
    id: "pa-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "pa",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-gurmukhi", title: "ਵੈਲੇਨਟਾਈਨ ਡੇ ਮੁਬਾਰਕ", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },

  // Birthday
  {
    id: "pa-bday-mubarkan",
    name: "Mubarkan",
    category: "birthday",
    lang: "pa",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-gurmukhi", title: "ਜਨਮਦਿਨ ਦੀਆਂ ਲੱਖ ਮੁਬਾਰਕਾਂ", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-bday-wish",
    name: "Birthday Wish",
    category: "birthday",
    lang: "pa",
    cover: { palette: "lavender", decoration: "ribbon-drift", titleFont: "font-gurmukhi", title: "ਤੁਹਾਡਾ ਜਨਮਦਿਨ ਸ਼ੁਭ ਹੋਵੇ", emoji: "🎁" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // Friendship
  {
    id: "pa-friend-yaar",
    name: "Yaar",
    category: "friendship",
    lang: "pa",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-gurmukhi", title: "ਮੇਰੇ ਯਾਰ ਲਈ", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },
  {
    id: "pa-friend-dosti",
    name: "Dosti",
    category: "friendship",
    lang: "pa",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-gurmukhi", title: "ਦੋਸਤੀ ਹਮੇਸ਼ਾ", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // Festivals (Punjab-heavy)
  {
    id: "pa-fest-lohri",
    name: "Lohri",
    category: "festival",
    lang: "pa",
    cover: { palette: "diya", decoration: "firework-bursts", titleFont: "font-gurmukhi", title: "ਲੋਹੜੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ", emoji: "🔥" },
    inside: { palette: "diya", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-fest-vaisakhi",
    name: "Vaisakhi",
    category: "festival",
    lang: "pa",
    cover: { palette: "sunset", decoration: "petal-shower", titleFont: "font-gurmukhi", title: "ਵਿਸਾਖੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ", emoji: "🌾" },
    inside: { palette: "sunset", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-fest-gurpurab",
    name: "Gurpurab",
    category: "festival",
    lang: "pa",
    cover: { palette: "indigo", decoration: "sparkle-trail", titleFont: "font-gurmukhi", title: "ਗੁਰਪੁਰਬ ਦੀਆਂ ਵਧਾਈਆਂ", emoji: "🪔" },
    inside: { palette: "indigo", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },
  {
    id: "pa-fest-diwali",
    name: "Diwali",
    category: "festival",
    lang: "pa",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-gurmukhi", title: "ਦੀਵਾਲੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-fest-rakhi",
    name: "Rakhi",
    category: "festival",
    lang: "pa",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-gurmukhi", title: "ਰੱਖੜੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ", emoji: "🪢" },
    inside: { palette: "amber", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },
  {
    id: "pa-fest-holi",
    name: "Holi",
    category: "festival",
    lang: "pa",
    cover: { palette: "holi", decoration: "colors", titleFont: "font-gurmukhi", title: "ਹੋਲੀ ਮੁਬਾਰਕ", emoji: "🎨" },
    inside: { palette: "holi", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },
  {
    id: "pa-fest-eid",
    name: "Eid",
    category: "festival",
    lang: "pa",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-gurmukhi", title: "ਈਦ ਮੁਬਾਰਕ", emoji: "🌙" },
    inside: { palette: "emerald", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // Everyday
  {
    id: "pa-everyday-shubh-saver",
    name: "Shubh Saver",
    category: "everyday",
    lang: "pa",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-gurmukhi", title: "ਸ਼ੁਭ ਸਵੇਰ", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-gurmukhi" },
    reveal: "rise",
  },
  {
    id: "pa-everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "pa",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-gurmukhi", title: "ਸ਼ੁਭ ਰਾਤਰੀ", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },
  {
    id: "pa-everyday-get-well",
    name: "Jaldi Theek Ho",
    category: "everyday",
    lang: "pa",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-gurmukhi", title: "ਜਲਦੀ ਠੀਕ ਹੋ ਜਾਓ", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },
  {
    id: "pa-everyday-vadhaaiyan",
    name: "Vadhaaiyan",
    category: "everyday",
    lang: "pa",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-gurmukhi", title: "ਵਧਾਈਆਂ!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-gurmukhi" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "pa-thanks-dhanyavad",
    name: "Dhanyavad",
    category: "thanks",
    lang: "pa",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-gurmukhi", title: "ਧੰਨਵਾਦ", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "pa-miss-yaad",
    name: "Yaad",
    category: "miss",
    lang: "pa",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-gurmukhi", title: "ਤੇਰੀ ਬਹੁਤ ਯਾਦ ਆਉਂਦੀ ਹੈ", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // Sorry
  {
    id: "pa-sorry-maafi",
    name: "Maafi",
    category: "sorry",
    lang: "pa",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-gurmukhi", title: "ਮੈਨੂੰ ਮਾਫ਼ ਕਰ ਦੇ", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-gurmukhi" },
    reveal: "fade",
  },

  // ================ TAMIL (ta) — full coverage ================
  // Love
  {
    id: "ta-love-kadhalikiren",
    name: "Kadhalikiren",
    category: "love",
    lang: "ta",
    cover: { palette: "rose", decoration: "hearts", titleFont: "font-tamil", title: "உன்னை காதலிக்கிறேன்", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-love-en-ulagam",
    name: "En Ulagam",
    category: "love",
    lang: "ta",
    cover: { palette: "lavender", decoration: "rose-rain", titleFont: "font-tamil", title: "நீ தான் என் உலகம்", emoji: "💖" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-love-anniversary",
    name: "Anniversary",
    category: "love",
    lang: "ta",
    cover: { palette: "amber", decoration: "petals", titleFont: "font-tamil", title: "திருமண தின வாழ்த்துக்கள்", emoji: "💞" },
    inside: { palette: "amber", decoration: "none", font: "font-tamil" },
    reveal: "rise",
  },

  // Valentine's Week
  {
    id: "ta-vw-rose",
    name: "Rose Day",
    category: "valentines-week",
    lang: "ta",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-tamil", title: "ரோஜா தின வாழ்த்துக்கள்", emoji: "🌹" },
    inside: { palette: "rose", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-vw-propose",
    name: "Propose Day",
    category: "valentines-week",
    lang: "ta",
    cover: { palette: "lavender", decoration: "sparkle-trail", titleFont: "font-tamil", title: "நீ என்னுடையது ஆவாயா?", emoji: "💍" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "rise",
  },
  {
    id: "ta-vw-chocolate",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "ta",
    cover: { palette: "amber", decoration: "chocolate-rain", titleFont: "font-tamil", title: "சாக்லேட் தின வாழ்த்துக்கள்", emoji: "🍫" },
    inside: { palette: "amber", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-vw-hug",
    name: "Hug Day",
    category: "valentines-week",
    lang: "ta",
    cover: { palette: "rose", decoration: "cupid-hearts", titleFont: "font-tamil", title: "ஒரு அணைப்பு உனக்காக", emoji: "🤗" },
    inside: { palette: "rose", decoration: "none", font: "font-tamil" },
    reveal: "rise",
  },
  {
    id: "ta-vw-valentine",
    name: "Valentine",
    category: "valentines-week",
    lang: "ta",
    cover: { palette: "rose", decoration: "rose-rain", titleFont: "font-tamil", title: "வாலெண்டைன்ஸ் டே வாழ்த்துக்கள்", emoji: "❤️" },
    inside: { palette: "rose", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },

  // Birthday
  {
    id: "ta-bday-vazhthukkal",
    name: "Vazhthukkal",
    category: "birthday",
    lang: "ta",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-tamil", title: "பிறந்தநாள் வாழ்த்துக்கள்", emoji: "🎂" },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-bday-iniya",
    name: "Iniya Pirandhanaal",
    category: "birthday",
    lang: "ta",
    cover: { palette: "lavender", decoration: "balloons", titleFont: "font-tamil", title: "இனிய பிறந்தநாள்", emoji: "🎈" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "rise",
  },

  // Friendship
  {
    id: "ta-friend-nanban",
    name: "Nanban",
    category: "friendship",
    lang: "ta",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-tamil", title: "என் நண்பனுக்காக", emoji: "🌟" },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-friend-natpu",
    name: "Natpu",
    category: "friendship",
    lang: "ta",
    cover: { palette: "mint", decoration: "stars", titleFont: "font-tamil", title: "நட்பு நிரந்தரம்", emoji: "🤝" },
    inside: { palette: "mint", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },

  // Festivals
  {
    id: "ta-fest-pongal",
    name: "Pongal",
    category: "festival",
    lang: "ta",
    cover: { palette: "sunset", decoration: "petal-shower", titleFont: "font-tamil", title: "இனிய பொங்கல்", emoji: "🌾" },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-fest-puthandu",
    name: "Puthandu",
    category: "festival",
    lang: "ta",
    cover: { palette: "emerald", decoration: "petal-shower", titleFont: "font-tamil", title: "இனிய தமிழ் புத்தாண்டு", emoji: "🪷" },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-fest-deepavali",
    name: "Deepavali",
    category: "festival",
    lang: "ta",
    cover: { palette: "diya", decoration: "diya-glow", titleFont: "font-tamil", title: "தீபாவளி நல்வாழ்த்துக்கள்", emoji: "🪔" },
    inside: { palette: "diya", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-fest-navratri",
    name: "Navratri",
    category: "festival",
    lang: "ta",
    cover: { palette: "holi", decoration: "petals", titleFont: "font-tamil", title: "நவராத்திரி வாழ்த்துக்கள்", emoji: "🪷" },
    inside: { palette: "holi", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-fest-christmas",
    name: "Christmas",
    category: "festival",
    lang: "ta",
    cover: { palette: "emerald", decoration: "snow-fall", titleFont: "font-tamil", title: "கிறிஸ்துமஸ் வாழ்த்துக்கள்", emoji: "🎄" },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-fest-new-year",
    name: "New Year",
    category: "festival",
    lang: "ta",
    cover: { palette: "midnight", decoration: "firework-bursts", titleFont: "font-tamil", title: "புத்தாண்டு நல்வாழ்த்துக்கள்", emoji: "🎆" },
    inside: { palette: "midnight", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "ta-fest-eid",
    name: "Eid",
    category: "festival",
    lang: "ta",
    cover: { palette: "emerald", decoration: "stars", titleFont: "font-tamil", title: "ஈத் முபாரக்", emoji: "🌙" },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },

  // Everyday
  {
    id: "ta-everyday-kalai-vanakkam",
    name: "Kalai Vanakkam",
    category: "everyday",
    lang: "ta",
    cover: { palette: "sunset", decoration: "petals", titleFont: "font-tamil", title: "காலை வணக்கம்", emoji: "☀️" },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "rise",
  },
  {
    id: "ta-everyday-iniya-iravu",
    name: "Iniya Iravu",
    category: "everyday",
    lang: "ta",
    cover: { palette: "midnight", decoration: "stars", titleFont: "font-tamil", title: "இனிய இரவு", emoji: "🌙" },
    inside: { palette: "midnight", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-everyday-get-well",
    name: "Seekiram Sukham",
    category: "everyday",
    lang: "ta",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-tamil", title: "சீக்கிரம் சுகமாக ஆகு", emoji: "🌷" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "ta-everyday-vazhthukkal",
    name: "Vazhthukkal",
    category: "everyday",
    lang: "ta",
    cover: { palette: "sunset", decoration: "confetti", titleFont: "font-tamil", title: "வாழ்த்துக்கள்!", emoji: "🎊" },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },

  // Thank You
  {
    id: "ta-thanks-nandri",
    name: "Nandri",
    category: "thanks",
    lang: "ta",
    cover: { palette: "emerald", decoration: "petals", titleFont: "font-tamil", title: "நன்றி", emoji: "🙏" },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },

  // Miss You
  {
    id: "ta-miss-miss-seygiren",
    name: "Miss Seygiren",
    category: "miss",
    lang: "ta",
    cover: { palette: "lavender", decoration: "cupid-hearts", titleFont: "font-tamil", title: "உன்னை மிஸ் செய்கிறேன்", emoji: "💭" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },

  // Sorry
  {
    id: "ta-sorry-mannithu",
    name: "Mannithu Vidu",
    category: "sorry",
    lang: "ta",
    cover: { palette: "lavender", decoration: "petals", titleFont: "font-tamil", title: "என்னை மன்னித்து விடு", emoji: "🥺" },
    inside: { palette: "lavender", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
];

export const getTemplate = (id) =>
  TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];

export const hasTemplate = (id) => TEMPLATES.some((t) => t.id === id);
