// Template registry. Each template composes palette + decoration + fonts + copy.
// Keep IDs short & stable — they go into share URLs.
export const TEMPLATES = [
  // ---------- LOVE ----------
  {
    id: "love-rose",
    name: "Rose Garden",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-dancing",
      title: "With All My Love",
      emoji: "🌹",
    },
    inside: {
      palette: "rose",
      decoration: "none",
      font: "font-caveat",
    },
    reveal: "burst",
  },
  {
    id: "love-tum-ho",
    name: "Tum Ho",
    category: "love",
    lang: "hi",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "तुम हो तो सब है",
      emoji: "💖",
    },
    inside: {
      palette: "lavender",
      decoration: "none",
      font: "font-devanagari",
    },
    reveal: "rise",
  },
  {
    id: "love-valentine",
    name: "Be Mine",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-playfair",
      title: "Happy Valentine's Day",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- BIRTHDAY ----------
  {
    id: "bday-confetti",
    name: "Confetti Pop",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-playfair",
      title: "Happy Birthday!",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "bday-balloons",
    name: "Balloon Party",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "balloons",
      titleFont: "font-dancing",
      title: "Make a Wish",
      emoji: "🎈",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "bday-janamdin",
    name: "Janamdin Mubarak",
    category: "birthday",
    lang: "hi",
    cover: {
      palette: "amber",
      decoration: "balloons",
      titleFont: "font-devanagari",
      title: "जन्मदिन मुबारक",
      emoji: "🎉",
    },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },

  // ---------- FRIENDSHIP ----------
  {
    id: "friend-bestie",
    name: "Best Friend",
    category: "friendship",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-caveat",
      title: "To My Favourite Human",
      emoji: "🌟",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "friend-yaar",
    name: "Yaari",
    category: "friendship",
    lang: "hi",
    cover: {
      palette: "mint",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "मेरे यार के नाम",
      emoji: "🤝",
    },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- FESTIVAL ----------
  {
    id: "fest-diwali",
    name: "Diwali Lights",
    category: "festival",
    lang: "en",
    cover: {
      palette: "diya",
      decoration: "diyas",
      titleFont: "font-playfair",
      title: "Happy Diwali",
      emoji: "🪔",
    },
    inside: { palette: "diya", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-holi",
    name: "Holi Hai",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "holi",
      decoration: "colors",
      titleFont: "font-devanagari",
      title: "होली है!",
      emoji: "🎨",
    },
    inside: { palette: "holi", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "fest-eid",
    name: "Eid Mubarak",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Eid Mubarak",
      emoji: "🌙",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "fest-rakhi",
    name: "Raksha Bandhan",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "amber",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "रक्षा बंधन मुबारक",
      emoji: "🪢",
    },
    inside: { palette: "amber", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "fest-christmas",
    name: "Merry Christmas",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "Merry Christmas",
      emoji: "🎄",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-new-year",
    name: "Happy New Year",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "confetti",
      titleFont: "font-playfair",
      title: "Happy New Year",
      emoji: "🎆",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- SORRY ----------
  {
    id: "sorry-soft",
    name: "I'm Sorry",
    category: "sorry",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "I'm Sorry",
      emoji: "🥺",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "sorry-forgive",
    name: "Forgive Me",
    category: "sorry",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "geometric",
      titleFont: "font-dancing",
      title: "Please Forgive Me",
      emoji: "🙇",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "sorry-maafi",
    name: "Maafi",
    category: "sorry",
    lang: "hi",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "माफ़ कर दो",
      emoji: "🤍",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- THANK YOU ----------
  {
    id: "thanks-grateful",
    name: "Thank You",
    category: "thanks",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "Thank You",
      emoji: "🙏",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "thanks-much-appreciated",
    name: "Much Appreciated",
    category: "thanks",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "You are a Gem",
      emoji: "✨",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "thanks-shukriya",
    name: "Shukriya",
    category: "thanks",
    lang: "hi",
    cover: {
      palette: "mint",
      decoration: "petals",
      titleFont: "font-devanagari",
      title: "शुक्रिया",
      emoji: "🌿",
    },
    inside: { palette: "mint", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- MISS YOU ----------
  {
    id: "miss-you-moon",
    name: "Missing You",
    category: "miss",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "I Miss You",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "miss-you-thinkingof",
    name: "Thinking of You",
    category: "miss",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "hearts",
      titleFont: "font-dancing",
      title: "Thinking of You",
      emoji: "💭",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "miss-yaad-aati",
    name: "Yaad Aati Hai",
    category: "miss",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "तुम्हारी याद आती है",
      emoji: "🕯️",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- MORE LOVE VARIETY ----------
  {
    id: "love-forever",
    name: "Forever Yours",
    category: "love",
    lang: "en",
    cover: {
      palette: "amber",
      decoration: "hearts",
      titleFont: "font-playfair",
      title: "Forever Yours",
      emoji: "💫",
    },
    inside: { palette: "amber", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "love-anniversary",
    name: "Happy Anniversary",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Happy Anniversary",
      emoji: "💞",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },

  // ---------- MORE BIRTHDAY ----------
  {
    id: "bday-minimal",
    name: "Another Year",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "mint",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Another Year Wiser",
      emoji: "🍰",
    },
    inside: { palette: "mint", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "bday-milestone",
    name: "Big Day",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "confetti",
      titleFont: "font-dancing",
      title: "It's Your Big Day!",
      emoji: "🥳",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- MORE FRIENDSHIP ----------
  {
    id: "friend-thanks-being-there",
    name: "Thanks for Being You",
    category: "friendship",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "stars",
      titleFont: "font-dancing",
      title: "Thanks for Being You",
      emoji: "💛",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },

  // ---------- EVERYDAY ----------
  {
    id: "everyday-good-night",
    name: "Good Night",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "stars",
      titleFont: "font-playfair",
      title: "Good Night",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-good-morning",
    name: "Good Morning",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Good Morning",
      emoji: "☀️",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "everyday-nice-day",
    name: "Have a Nice Day",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "mint",
      decoration: "petals",
      titleFont: "font-dancing",
      title: "Have a Nice Day",
      emoji: "🌼",
    },
    inside: { palette: "mint", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-get-well",
    name: "Get Well Soon",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petals",
      titleFont: "font-playfair",
      title: "Get Well Soon",
      emoji: "🌷",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "everyday-congrats",
    name: "Congrats!",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-dancing",
      title: "Congratulations!",
      emoji: "🎊",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "everyday-shubh-ratri",
    name: "Shubh Ratri",
    category: "everyday",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "stars",
      titleFont: "font-devanagari",
      title: "शुभ रात्रि",
      emoji: "🌃",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },

  // ---------- VALENTINE'S WEEK (Feb 7-14) ----------
  {
    id: "vw-rose-day",
    name: "Rose Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-dancing",
      title: "Happy Rose Day",
      emoji: "🌹",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "vw-propose-day",
    name: "Propose Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "Will You Be Mine?",
      emoji: "💍",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-chocolate-day",
    name: "Chocolate Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "amber",
      decoration: "chocolate-rain",
      titleFont: "font-dancing",
      title: "Happy Chocolate Day",
      emoji: "🍫",
    },
    inside: { palette: "amber", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "vw-teddy-day",
    name: "Teddy Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "teddy-drift",
      titleFont: "font-dancing",
      title: "Happy Teddy Day",
      emoji: "🧸",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-promise-day",
    name: "Promise Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "indigo",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "My Promise to You",
      emoji: "🤞",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "vw-hug-day",
    name: "Hug Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "cupid-hearts",
      titleFont: "font-dancing",
      title: "Sending You a Hug",
      emoji: "🤗",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "vw-kiss-day",
    name: "Kiss Day",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "petal-shower",
      titleFont: "font-dancing",
      title: "A Kiss for You",
      emoji: "💋",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "vw-valentines",
    name: "Happy Valentine's",
    category: "valentines-week",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-playfair",
      title: "Be My Valentine",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },

  // ---------- MORE FESTIVALS (rich) ----------
  {
    id: "fest-ganesh",
    name: "Ganesh Chaturthi",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "diya",
      decoration: "diya-glow",
      titleFont: "font-devanagari",
      title: "गणपति बाप्पा मोरया",
      emoji: "🕉️",
    },
    inside: { palette: "diya", decoration: "none", font: "font-devanagari" },
    reveal: "rise",
  },
  {
    id: "fest-janmashtami",
    name: "Janmashtami",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "indigo",
      decoration: "sparkle-trail",
      titleFont: "font-devanagari",
      title: "जय श्री कृष्ण",
      emoji: "🦚",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-devanagari" },
    reveal: "fade",
  },
  {
    id: "fest-navratri",
    name: "Navratri",
    category: "festival",
    lang: "hi",
    cover: {
      palette: "holi",
      decoration: "petal-shower",
      titleFont: "font-devanagari",
      title: "नवरात्रि की शुभकामनाएँ",
      emoji: "🪷",
    },
    inside: { palette: "holi", decoration: "none", font: "font-devanagari" },
    reveal: "burst",
  },
  {
    id: "fest-pongal",
    name: "Pongal",
    category: "festival",
    lang: "en",
    cover: {
      palette: "sunset",
      decoration: "sparkle-trail",
      titleFont: "font-playfair",
      title: "Happy Pongal",
      emoji: "🌾",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "fest-onam",
    name: "Onam",
    category: "festival",
    lang: "en",
    cover: {
      palette: "emerald",
      decoration: "petal-shower",
      titleFont: "font-playfair",
      title: "Happy Onam",
      emoji: "🌼",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "fest-diwali-rich",
    name: "Diwali Glow",
    category: "festival",
    lang: "en",
    cover: {
      palette: "diya",
      decoration: "diya-glow",
      titleFont: "font-playfair",
      title: "Shubh Deepawali",
      emoji: "🪔",
    },
    inside: { palette: "diya", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-new-year-rich",
    name: "New Year Fireworks",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "firework-bursts",
      titleFont: "font-dancing",
      title: "Happy New Year!",
      emoji: "🎆",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "fest-christmas-rich",
    name: "Christmas Snow",
    category: "festival",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "snow-fall",
      titleFont: "font-dancing",
      title: "Merry Christmas",
      emoji: "🎄",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },

  // ---------- MORE RICH EVERYDAY / LOVE ----------
  {
    id: "everyday-sweet-dreams",
    name: "Sweet Dreams",
    category: "everyday",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "sparkle-trail",
      titleFont: "font-dancing",
      title: "Sweet Dreams",
      emoji: "🌙",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "fade",
  },
  {
    id: "love-always",
    name: "I Love You Always",
    category: "love",
    lang: "en",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-dancing",
      title: "I Love You, Always",
      emoji: "💖",
    },
    inside: { palette: "rose", decoration: "none", font: "font-caveat" },
    reveal: "burst",
  },
  {
    id: "birthday-rich-wish",
    name: "Birthday Wish",
    category: "birthday",
    lang: "en",
    cover: {
      palette: "lavender",
      decoration: "ribbon-drift",
      titleFont: "font-dancing",
      title: "Wishing You the Moon",
      emoji: "🎁",
    },
    inside: { palette: "lavender", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },
  {
    id: "miss-long-distance",
    name: "Across the Miles",
    category: "miss",
    lang: "en",
    cover: {
      palette: "midnight",
      decoration: "cupid-hearts",
      titleFont: "font-playfair",
      title: "Across the Miles",
      emoji: "✈️",
    },
    inside: { palette: "midnight", decoration: "none", font: "font-caveat" },
    reveal: "rise",
  },

  // ---------- REGIONAL LANGUAGES ----------
  {
    id: "regional-marathi-vadhdiwas",
    name: "Vadhdivas",
    category: "birthday",
    lang: "mr",
    cover: {
      palette: "sunset",
      decoration: "balloons",
      titleFont: "font-marathi",
      title: "वाढदिवसाच्या हार्दिक शुभेच्छा",
      emoji: "🎂",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "regional-marathi-prem",
    name: "Prem",
    category: "love",
    lang: "mr",
    cover: {
      palette: "rose",
      decoration: "rose-rain",
      titleFont: "font-marathi",
      title: "तू माझं सर्वस्व",
      emoji: "❤️",
    },
    inside: { palette: "rose", decoration: "none", font: "font-marathi" },
    reveal: "burst",
  },
  {
    id: "regional-tamil-piranthanaal",
    name: "Piranthanaal",
    category: "birthday",
    lang: "ta",
    cover: {
      palette: "sunset",
      decoration: "confetti",
      titleFont: "font-tamil",
      title: "பிறந்தநாள் வாழ்த்துக்கள்",
      emoji: "🎉",
    },
    inside: { palette: "sunset", decoration: "none", font: "font-tamil" },
    reveal: "burst",
  },
  {
    id: "regional-tamil-nandri",
    name: "Nandri",
    category: "thanks",
    lang: "ta",
    cover: {
      palette: "emerald",
      decoration: "petals",
      titleFont: "font-tamil",
      title: "நன்றி",
      emoji: "🙏",
    },
    inside: { palette: "emerald", decoration: "none", font: "font-tamil" },
    reveal: "fade",
  },
  {
    id: "regional-bangla-shubho-jonmodin",
    name: "Shubho Jonmodin",
    category: "birthday",
    lang: "bn",
    cover: {
      palette: "indigo",
      decoration: "balloons",
      titleFont: "font-bangla",
      title: "শুভ জন্মদিন",
      emoji: "🎈",
    },
    inside: { palette: "indigo", decoration: "none", font: "font-bangla" },
    reveal: "rise",
  },
  {
    id: "regional-bangla-bhalobasha",
    name: "Bhalobasha",
    category: "love",
    lang: "bn",
    cover: {
      palette: "rose",
      decoration: "hearts",
      titleFont: "font-bangla",
      title: "তোমায় ভালোবাসি",
      emoji: "💗",
    },
    inside: { palette: "rose", decoration: "none", font: "font-bangla" },
    reveal: "burst",
  },
];

export const getTemplate = (id) =>
  TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];

export const hasTemplate = (id) => TEMPLATES.some((t) => t.id === id);
